### ISSUE TITLE
bitFlyerDataStoreのポジション数量が正しくない

### ISSUE THREAD

**Issue by MtkN1** [MtkN1/pybotters#103]
## 課題

Discordより:
https://discord.com/channels/832651305155297331/832653694839160892/925485784851689472

報告によると、bitFlyer側からWebSocketで送られてくるsizeが正しくないようである。
データを取得してDataStoreの計算がおかしいのか、WebSocket側が正しくないのかを検証しDataStoreに問題があれば修正する。

## チェックリスト

- [ ] 検証

**Comment by shinji19** [comment]
bitFlyer btc-fxでポジションが0の状況から購入・売却すると発生しました。
0.01 購入 -> ポジション=0.01
0.02 売却 -> ポジション=0

新しく作られたポジションの追加をしていないのが原因のような気がしました。
https://github.com/MtkN1/pybotters/blob/main/pybotters/models/bitflyer.py#L270-L279
