### ISSUE TITLE
GMOCoinDataStoreがTypeErrorで落ちる。

### ISSUE THREAD

**Issue by kohilin** [MtkN1/pybotters#122]
## 課題

下記のエラーでGMOCoinDataStoreが落ちてしまいます。

`cast(list[Item], data)`は`cast(list, data)`の間違いではないでしょうか。

```
Traceback (most recent call last):
    ...
    self._insert(cast(list[Item], data))
TypeError: 'type' object is not subscriptable
```

再現コードと当該箇所（`cast(list[Item], data)`となっている箇所は他にもいくつかありました）です。

```python
async def main():
    async with pybotters.Client(base_url="https://api.coin.z.com") as client:
        store = pybotters.GMOCoinDataStore()
        await store.initialize(
            client.get("/private/v1/positionSummary"),
        )
```

https://github.com/MtkN1/pybotters/blob/5f3558a50e93dbb33597579b240e967a40630bc3/pybotters/models/gmocoin.py#L378

## チェックリスト

- [x] Fix

**Comment by kohilin** [comment]
python 3.9.7にあげると正常に動くようになりました。

以下当方で試した環境です。

- 正常に動いたもの：python 3.9.7・typing-extensions==3.10.0.0
- 上記のエラーが出たもの：python 3.8.8・typing-extensions=3.10.0.0

typing-extensionsは詳しくないのですが、上記の記法は新しめのpythonでのみサポートされているのように思いました。

**Comment by MtkN1** [comment]
レポートありがとうございます！
エラーが再現される事は確認しました。

> cast(list[Item], data)はcast(list, data)の間違いではないでしょうか。

`list[Item]` 型を該当メソッドに渡すので、型アノテーションとしては間違いではありません。
しかし、指摘の通り `cast(list[Item], data)` はPython 3.9未満ではコードとしてはエラーが発生するようです。

これはPR #92 https://github.com/MtkN1/pybotters/pull/92/commits/b744469b49a9dfe8938eeef9e0095e9abba273a3#diff-70d03f7374b991e4ed0cf280951f8c425f5b3275616ac1d3c0c1a61872916583 の変更が起因していそうです。

このPRでは `list[Item]` といった標準コレクションを利用した型アノテーションの書き方をできるようにしています。 
(標準コレクションについては詳しくはPEP585を参照してください https://www.python.org/dev/peps/pep-0585/)
該当Diff変更前のtypingモジュールでの `cast(List[Item], data)` を試したらエラーは発生しませんでした。

Python 3.9未満での標準コレクションと `typing.cast` になんらかの問題があると思いますので、分かり次第該当エラーが発生しないように修正したいと思います。

**Comment by MtkN1** [comment]
言語サーバー(Pylance)の警告を頼りに、型注釈を引用符で囲みました。

> Subscript for class "list" will generate runtime exception; enclose type annotation in quotes

castは文字列でのアノテーションを受け付けているみたいなので、これでFixします。

**Comment by kohilin** [comment]
検証修正ありがとうございます！お陰様でいつも非同期プログラミング楽しませていただいています。
