### ISSUE TITLE
BinanceのbookTicker使用時にKeyErrorが発生する

### ISSUE THREAD

**Issue by yama1105** [MtkN1/pybotters#123]
大変便利なライブラリを作成していただいてありがとうございます。
Binance WebSocketにてbookTickerを取得し、ハンドラーでDataStore.onmessageする際に`KeyError: 'e'`が発生するのでご報告します。

### 書いたコード(一部)
```
~~~
# BinanceとWebsocketを接続
        binance_ws = await client.ws_connect(
            url="wss://stream.binance.com:9443/ws",
            send_json=[
                # 約定データとbookTicker
                {"method": "SUBSCRIBE",
                 "params": ["ethusdt@trade", "ethusdt@bookTicker"],
                 "id": 1}],
            hdlr_json=binance_store.onmessage
        )
~~~
```

### トレースバック
```
Traceback (most recent call last):
  File "\lib\site-packages\pybotters\ws.py", line 99, in ws_run_forever
    hdlr_json(data, ws)
  File "\lib\site-packages\pybotters\store.py", line 290, in onmessage
    self._onmessage(msg, ws)
  File "\lib\site-packages\pybotters\models\binance.py", line 73, in _onmessage
    event = data['e'] if isinstance(data, dict) else data[0]['e']
KeyError: 'e'
```

## 私見
Binance APIのdocsでは`<symbol>@bookTicker`のペイロード例は
```
{
  "u":400900217,     // order book updateId
  "s":"BNBUSDT",     // symbol
  "b":"25.35190000", // best bid price
  "B":"31.21000000", // best bid qty
  "a":"25.36520000", // best ask price
  "A":"40.66000000"  // best ask qty
}
```
[引用元:binance-docs.github.io](https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-book-ticker-streams)
となっているので、レスポンスJSON内に"event"の項目が存在せず、
https://github.com/MtkN1/pybotters/blob/5f3558a50e93dbb33597579b240e967a40630bc3/pybotters/models/binance.py#L84-L85
以上のコードにて適切にDataStoreにbookTickerデータが入力されない状態であると考えています。

**Comment by MtkN1** [comment]
レポートありがとうございます！

BinanceDataStoreですが、取引種別の実装状況としては今のところ「USDⓈ-M Futures」のみとなっています。
https://github.com/MtkN1/pybotters/tree/5f3558a50e93dbb33597579b240e967a40630bc3#-exchanges

WSエンドポイント `wss://stream.binance.com:9443/ws` は現物向けですので、まだ対応していません。
このエンドポイントから受信するペイロードは互換性がないので、現物のbookTickerを受信すると仰るようにKeyErrorなど予期せぬ例外が発生します。

参考:bookTicker(USDⓈ-M Futures)のペイロード
```js
{
  "e":"bookTicker",         // event type
  "u":400900217,            // order book updateId
  "E": 1568014460893,       // event time
  "T": 1568014460891,       // transaction time
  "s":"BNBUSDT",            // symbol
  "b":"25.35190000",        // best bid price
  "B":"31.21000000",        // best bid qty
  "a":"25.36520000",        // best ask price
  "A":"40.66000000"         // best ask qty
}
```

「USDⓈ-M Futures」以外の取引種別は今後実装予定です。
(それはそうと、現物に "e" がないのは由々しき問題です...)

なので現状、現物bookTickerを扱いたいとなると独自のDataStore実装が必要です。
bookTickerだけ1つ程度であればそのサンプルコードを書けますがご必要でしょうか？

**Comment by yama1105** [comment]
USDⓈ-M Futuresのみの対応でしたのですね。
完全に見落としておりお騒がせいたしました。
申し訳ありません。

さて自分が欲しかった情報としては特段現物商品でなくてもよく、
ByBitのUSDT無期限のAPIを利用して既にしたいことは実現いたしました。
なのでサンプルコードはご提供いただかなくても大丈夫です。
ご厚意に厚く感謝いたします。

ご対応ありがとうございました。
