### ISSUE TITLE
テストの際にOKXのデモトレードが使用不可

### ISSUE THREAD

**Issue by Rilm2525** [MtkN1/pybotters#154]
auth.py
327行目 - 333行目のヘッダーを
{
    "OK-ACCESS-KEY": key,
    "OK-ACCESS-SIGN": sign,
    "OK-ACCESS-TIMESTAMP": timestamp,
    "OK-ACCESS-PASSPHRASE": passphrase,
    "Content-Type": "application/json",
}
から
{
    "OK-ACCESS-KEY": key,
    "OK-ACCESS-SIGN": sign,
    "OK-ACCESS-TIMESTAMP": timestamp,
    "OK-ACCESS-PASSPHRASE": passphrase,
    "x-simulated-trading": "1",
    "Content-Type": "application/json",
}
に変更することにより応急処置はできました。
オプションなどで切り替えられるようにしていただけるとありがたいです。

**Comment by MtkN1** [comment]
ご報告ありがとうございます。

OKXのデモトレードですが、ヘッダー `"x-simulated-trading": "1"` を ** **クライアントに設定する** ** ことにより pybotters は OKX のデモトレード API を認識する機構を設けられています。
Wikiのドキュメントが整備されておらず恐縮ですが、リリースノートに記載しています。

https://github.com/MtkN1/pybotters/releases/tag/v0.11.0#:~:text=Demo%20Trading

```py
async def main():
    apis = {"okx_demo": ["OKX_API_KEY", "OKX_API_SECRET", "YOUR_PASSPHRASE"]}
    headers = {"x-simulated-trading": "1"}
    async with pybotters.Client(apis=apis, headers=headers) as client:
        ...
```

これによって `okx_demo` の API キーで認証が行われます。
つまり、 ** **このヘッダーを設定することがデモトレードを切り替えるオプション** ** になっています。

他の取引所はであれば基本的に `https://testnet.xxx.com` のように別ホストで testnet が稼働しているのですが、OKX に関しては同一ホストでデモトレードが稼働しておりヘッダーで判別するしかないので、このような仕様となっています。

参考

OKX API ドキュメント (#デモトレード)
https://www.okx.com/docs-v5/en/#overview-demo-trading-services

**Comment by Rilm2525** [comment]
返信有難うございます。
ヘッダーが指定できるのですね
私の確認不足でした
