### ISSUE TITLE
Binance Spotのデータストア実装

### ISSUE THREAD

**Issue by ko0hi** [MtkN1/pybotters#187]
Binance Spot用のデータストアの実装を試みています。

まずは、Binance Spotで提供されている[Marketデータの各配信](https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams)について、BinanceDataStoreのDataStoreおよび`_onmessage`を流用できるかチェックしました。

結果としては**bookTickerのみBinanceDataStoreのものを流用できませんでした**。

そこで実装方針について相談したくissueを立てています。
具体的には、`BinanceSpotDataStore`（仮名）を（１）`BinanceDataStore`を継承して実装するか、（２）独立して実装するか、という点です

（[Individual Symbol Rolling Window Statistics Streams](https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-rolling-window-statistics-streams)に関しては、BinanceDataStoreでも未対応だったため除外しています。）

## 問題箇所

spotのbookTickerの配信に ["e"フィールドが含まれていない](https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-book-ticker-streams)ために[イベント判別ロジックの箇所](https://github.com/MtkN1/pybotters/blob/main/pybotters/models/binance.py#L86)で `KeyError`が発生しました。

```python
event = data["e"] if isinstance(data, dict) else data[0]["e"]
```
スポットの配信例
```
{
  "u":400900217,     // order book updateId
  "s":"BNBUSDT",     // symbol
  "b":"25.35190000", // best bid price
  "B":"31.21000000", // best bid qty
  "a":"25.36520000", // best ask price
  "A":"40.66000000"  // best ask qty
}
```

USD-Mの配信例
```
{
  "e":"bookTicker",         // event type
  "u":400900217,            // order book updateId
  "E": 1568014460893,       // event time
  "T": 1568014460891,       // transaction time
  "s":"BNBUSDT",            // symbol
  "b":"25.35190000",        // best bid price
  "B":"31.21000000",        // best bid qty
  "a":"25.36520000",        // best ask price
  "A":"40.66000000"         // best ask qty
}
```

#### 良い点
bookTicker以外はそのまま使えたので継承して実装することで多くの部分を再利用できます。
bookTickerの問題に関しても、イベント判別ロジックを修正すればオーバーライドせずに対応できると思います（以下一例です）。

```python
_data = data if isinstance(data, dict) else data[0]
if "e" in _data:
    event = _data["e"]
else:
    # e(vent) fieldがないチャンネル用のロジック
    if msg["stream"].endswith("bookTicker"):
        # spot bookTickerは"e"フィールドがない
        # https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-book-ticker-streams  # noqa
        event = "bookTicker"
    else:
        event = None
```

#### 懸念点

- `BinanceSpotDataStore`用のロジックが `BinanceDataStore`に存在してしまう
- `BinanceSpotDataStore`では使用しないDataStoreをメンバ変数（markprice, liquidation, continuouskline）に持ってしまう

二つ目に関しては propetyメソッドをオーバーライドしてエラーを出すなどできますが、紛らわしいのは確かです。

```python
class BinanceSpotDataStore(BinanceDataStore):
    @property
    def markprice(self) -> "MarkPrice":
        raise RuntimeError("Unsupported store: `markprice`")
```

#### 良い点
（１）の懸念点がなくなります

#### 懸念点
- コードの重複が生じる
  - _init
  - initialize
  - _onmessage
  - 各種properties

---- 

どう思われますか？
Binanceは（~~どこぞの取引所と異なり~~）Spot/USD-Mでかなり統一されているだけに悩みどころだと思っています。
第３の選択肢として、`BinanceDataStoreBase`みたいなBinanceのDataStoreManager用の抽象クラスを作って、`BinanceUSDMDataStore`・`BinanceSpotDataStore`・`BinanceCoinMDataStore`のように定義するのもありですが、そうすると現行`BinanceDataStore = BinanceUSDMDataStore`となっている点と合わなくなるのが気になります（こうするなら`BinanceDataStore = BinanceUSDMDataStore`のaliasを残すことにはなると思いますが・・・）。

**Comment by MtkN1** [comment]
Issue 起票・ご提案ありがとうございます！🙌

以前 Binance Spot のデータを試した時に "e" フィールドがなかったので暫く諦めていました。
...なるほど、その時 bookTicker しか試していなかったようです。
データ構造が違うと思い込んでいましたが、Spot も既存の onmessage でハンドリングできそうなのですね。

実装方針については、主要情報（板、トレード、ローソク足、ポジションなど）のデータ構造が統一されているのであれば、**案3の抽象クラスを作る** 方針にしたいと思います。 案1での存在しないプロパティが継承されてしまうのは避けたいです。

命名については
- `BinanceDataStoreBase` (抽象クラス)
- `BinanceSpotDataStore`
- `BinanceUSDSMDataStore` (正式表記に準拠)
- `BinanceCOINMDataStore` (正式表記に準拠)

になります。(ストアクラスの命名は PEP8 の規則を無視して取引所・アセット固有名詞の正式名に準拠しています #69)
既存の `BinanceDataStore` は Deprecated にして `BinanceDataStore = BinanceUSDSMDataStore` の alias を残します。

もし ~Bybit~ どこぞの取引所のように完全に違ったり、データが似ているが共通化するほどでもない場合は抽象クラスはなくして冗長的にクラスを分けましょう。

指針としてはこのような感じです。 可能であればコントリビュート頂けるとありがたいです！

**Comment by ko0hi** [comment]
ありがとうございます！

> 装方針については、主要情報（板、トレード、ローソク足、ポジションなど）のデータ構造が統一されているのであれば、案3の抽象クラスを作る 方針にしたいと思います。

承知しました。自分も工数は増えどもそのように実装した方が良いだろうな、と感じていました。

その他指針の共有ありがとうございます。コントリビュートさせて頂きたいと思います。

規模がBinanceのDataStore全体の改修という具合になったので、別issueを立てましてそちらで作業していこうと思います。
まずはCoin-Mがどのくらい共通化できそうかの確認をします！
