### ISSUE TITLE
Binance Spotでprivate weboscoketのlisten keyを取得する際のAuthエラー

### ISSUE THREAD

**Issue by ko0hi** [MtkN1/pybotters#190]
Binance Spotにて[UserDataStream websocketのlisten key](https://binance-docs.github.io/apidocs/spot/en/#listen-key-spot)を取得しようとすると下記のエラーが出ます。

```
 {'code': -1101, 'msg': "Too many parameters; expected '0' and received '2'."}
```

問題としては #44 と同じなのですが、private websocketのlisten keyの取得にはauthが必要なため 「`auth=None`を与えることで回避する」という方法を取ることができません。

回避策としては

①. Binanceのauth内で条件分岐する
②. ①に加え、spot用のauthは別に作ることで見通しを良くする

くらいしか思いついてないのですが、他にどういった対処法が考えうるでしょうか。

なお、[COIN-Mの方](https://binance-docs.github.io/apidocs/delivery/en/#user-data-streams)では現状のauthで問題なく取得することができました。

サンプルコード

```python
import asyncio
import pybotters

async def main():
    async with pybotters.Client(apis=..., base_url="https://api.binance.com") as client:
        d = await (await client.post("/api/v3/userDataStream")).json()
        print(d)  #  {'code': -1101, 'msg': "Too many parameters; expected '0' and received '2'."}

if __name__ == "__main__":
    asyncio.run(main())

```

関連issue・PR： #187 #188 #189

**Comment by ko0hi** [comment]
[この部分](https://github.com/MtkN1/pybotters/blob/main/pybotters/auth.py#L92)を以下のように変更すると、listen keyを取得できるのは確認しました。やはり #44同様、`timestamp`と`signature`が入っていることが問題のようです。


```python
data.update({"timestamp": expires})
body = FormData(data)()
signature = hmac.new(secret, body._value, hashlib.sha256).hexdigest()
body._value += f"&signature={signature}".encode()
body._size = len(body._value)
kwargs.update({"data": body})
```
↓
```python
data.update({"timestamp": expires})
# modified
body = (
    FormData(data)() if url.path != "/api/v3/userDataStream" else FormData()()
)
signature = hmac.new(secret, body._value, hashlib.sha256).hexdigest()
# modified
if url.path != "/api/v3/userDataStream":
    body._value += f"&signature={signature}".encode()
body._size = len(body._value)
kwargs.update({"data": body})
```

**Comment by MtkN1** [comment]
Issue 起票ありがとうございます！
内容理解しました。 こちらもで試したところ、再現確認しました。

これはどういう事象か探ってみたところ、公式ドキュメントにしっかりと記載がありました。

Security Type | Description
-- | --
NONE | Endpoint can be accessed freely.
TRADE | Endpoint requires sending a valid API-Key and signature.
MARGIN | Endpoint requires sending a valid API-Key and signature.
USER_DATA | Endpoint requires sending a valid API-Key and signature.
USER_STREAM | Endpoint requires sending a valid API-Key.
MARKET_DATA | Endpoint requires sending a valid API-Key.

引用: https://binance-docs.github.io/apidocs/spot/en/#endpoint-security-type

pybotters は現状これに準拠していないようです。
USER_STREAM と MARKET_DATA についての「ヘッダーに API-Key は必要だが、signature が必要ない」のパターンに対応できておらず、 pybotters の認証を掛ければ _Too many parameters_ になり、認証を掛けなければ _API-key format invalid_ になる、と言ったところですね。
しかも USDⓈ-M と COIN-M では再現しないとのことなので、Spot / Margin API サーバーのみの仕様のようですね。

Spot のみ対応するか、ドキュメントにある通りに体系的に全て対応するかは考えますが、修正はこちらで行います。

## 対応方法

**＊＊Draft PR #189 のブランチで、コメントして頂いた修正パッチをコミットしてして頂けますか？＊＊**
取り敢えず認証が通れば当 Issue は close にし、認証がドキュメントに完全に準拠していない点については問題だと思うので、別 Issue を切ってエンドポイント別に準拠するのかどうかなど本対応したいと思います。

ご協力お願いします 🙇‍♂️

**Comment by ko0hi** [comment]
確認・対応方法の指示ありがとうございます！

こちらのコミットで #189 のドラフトブランチにはパッチを適用して対応しましたので、こちらcloseします。

当該コミット：https://github.com/MtkN1/pybotters/pull/189/commits/492f1725ba2dcf063bcdc85e4dfebeef6289ef87
