### ISSUE TITLE
BinanceのREST APIの内パラメータエラーで失敗するものがある。

### ISSUE THREAD

**Issue by shidokamo** [MtkN1/pybotters#220]
BinanceのいくつかのREST APIがエラーになるのを確認しました。
自分が確認した範囲では、SpotのAPIのうちいくつかは、timestampなどのパラメータが厳密に不要で、逆にtimestampなどのパラメータが入ってしまっているとパラメータのエラーを返すようです。
たとえば、Order Bookの以下のAPIが該当します。

![image](https://user-images.githubusercontent.com/49507117/217725087-8999b405-8503-4d10-9df6-3418a9ae5702.png)

エラーログは取り忘れました。
手元で修正して動作確認したのでプルリクエストを送ります。

**Comment by MtkN1** [comment]
Issue 提起 & PR ありがとうございます！

Binance Spot における Public なエンドポイントにリクエストすると認証エラーとなるのは既知の問題であり、回避策が実装済みとなっています。

- https://github.com/MtkN1/pybotters/issues/44

pybotters はリクエストの認証が自動で有効になっているので、Binance Spot の Public なエンドポイントでは今回のように無駄に認証を付与していることでエラーレスポンスとなってしまいます。 そこで上記 Issue ではリクエストの引数 `auth=None` とすると認証を無効化できる機能が実装され、これにより正しくリクエストすることが可能となっています。

```py
async def main():
    async with pybotters.Client(apis=apis) as client:
        r = await client.get('https://api.binance.com/api/v3/depth', params={'symbol': 'BTCUSDT', 'limit': '10'}, auth=None)
        print(await r.json())
```

Reference ページ: https://github.com/MtkN1/pybotters/wiki/Reference#:~:text=auth%3DNone

---

PR 頂いた変更では Binance Spot Public エンドポイントのパスをハードコードすることで認証を回避する形となっていますが、現状 `auth=None` の形で回避策を実装しているのは、出来る限りエンドポイントのハードコードをなくし Binance 側が Public なエンドポイントを増やした場合においても pybotters の認証ロジックを更新することなく恒久的に対応できる手段となる為です。

** **しかし `auth=None` の仕様は明確さや案内が不十分であることから、これまでにもしばしユーザーの混乱を招いていることは確かです。** **

しかもこの現象は Binance Spot のみであり、Binance USDⓈ-M Futures や現状 pybotters が対応している他の全ての取引所では Public なエンドポイントに認証付きでリクエストしても弾かれることはありません。 その為ユーザーの利便性を鑑みても Binance Spot のみ頂いた PR の変更のようにハードコードしてしまっても構わないかな、と少し揺らいでいるところです。

一先ず PR は取り下げず残して頂けますでしょうか。 Binance API の Changelog の具合や全体的な影響をみてもう少し検討してみます。

**Comment by shidokamo** [comment]
まちゅけんさん、どうもお忙しい中お時間取らせてしまって、気も使わせてしまってすいません！
こっちのIssueに書いてあるよ〜くらいのカジュアルな感じでクローズしていただいても僕は全然大丈夫なんで！
他のIssueをよく調べておくべきでした。

ご説明頂いて、よく背景が分かりました。
確かにBinanceの仕様が不明確な中で、エンドポイントの追加に延々と追従していくのはナンセンスですね。
pybottersは、全体をシンプルにしつつ、基本的に取引所の仕様を各自ユーザがよく理解して使うもの、という思想の元に作られているようにも見えるので、auth=Noneを提供してユーザに対応を委ねるほうが、pybottersらしいようにも思えますね。
とりあえず手元の方では、auth=Noneを使って対応したいと思います。
色々と助かっています。ありがとうございます！

**Comment by MtkN1** [comment]
(検討コメです。レス不要です)

Binance Spot API Docs を読み漁っていたたころ、本件解決の助けになりそうな情報を新たに見つけた。

## 1. _The base endpoint https://data.binance.com_

https://binance-docs.github.io/apidocs/spot/en/#general-api-information

![image](https://user-images.githubusercontent.com/51289448/218325287-bffb79a8-7a23-400d-be37-45a73ad6ef9a.png)

_https://data.binance.com_ というベースエンドポイントが新たに公開されており、自動認証付与によって失敗してしまう Public API は別途ここからもアクセスができるようになっているらしい。

👉 `auth=None` の対策と大差はないが、自動認証付与によって失敗してしまう Public API のリクエストは _https://data.binance.com_ のベースエンドポイントで行うようドキュメントに案内を追加してもよいかもしれない。 (pybotters の認証ホストマッピングの対象外になる)

## 2. 5 年間で追加された Public エンドポイント は 1 つのみ

Change Log 上で追加された Public なエンドポイントは _GET /api/v3/uiKlines_ (2022-08-23) の 1 つのみだった。 非常にサイクルが長いといえる。

👉 自動認証付与によって失敗する Public な API (_Endpoint security type: NONE_) も 1. の欄に網羅的に記載されているので、それをもとにハードコードしてしまってもよいかもしれない。

---

ユーザーアクションを求めるか、ハードコードで対応するかいずれにしても本 Issue は _Endpoint security type: NONE_ のみ注目しているので、関連 Issue https://github.com/MtkN1/pybotters/issues/192 と対応を合わせる必要がある。

**Comment by MtkN1** [comment]
pybotters が提供するべきものは与えられたリクエスト情報に認証を付与することであり、それが Public なものであるかは上位のラッパー的なものの機能だと考える。 なのでむしろ *** ***認証が無効なエンドポイントに認証を付与して、無効だというレスポンスを得る事が出来る*** *** のが pybottesr のレイヤーであるべきといえる。

よって本 Issue はクローズします。
