### ISSUE TITLE
GMOコインのWebSocket API制限により複数購読ができない

### ISSUE THREAD

**Issue by MtkN1** [MtkN1/pybotters#50]
## 課題

- pybottersは `ws_connect` メソッド `send_json` 引数にリストで渡すことでsubscribeメッセージを非同期で投げる仕様としている
- しかしGMOコインのWebSocket API(Public/Private)においては以下の様な制限があるため `{"error":"ERR-5003 Request too many."}` が返却されて2つ以上のチャンネルの購読ができない
- https://api.coin.z.com/docs/#restrictions
  - > 同一IPからのリクエスト(subscribe, unsubscribe)は、1秒間1回を上限とします。
- 詳細はsupermomonga氏のGist(GMOコインへの要望書)を参照
  - https://gist.github.com/supermomonga/2283f57bef66a69ab158072e8c3a8c28

## 検討

1. `ws_connect` メソッドに `onopen` のような引数を持たせて購読についてもユーザーに制御可能にする
1. GMOコインのみ分岐させてpybotters側で別制御にする

## チェックリスト

- [x] 実装
- [x] Wiki

**Comment by supermomonga** [comment]
ざっくりと対応するのであれば `onopen` 関数を渡す方針で良いと思います。

```
def some_onopen_func(ws: aiohttp:ClientWebSocketResponse):
    await ws.send_json(...) # チャンネルAを購読
    await asyncio.sleep(1.5) # 少しバッファを取って 1.5 秒待機
    await ws.send_json(...) # チャンネルBを購読
    await asyncio.sleep(1.5) # 少しバッファを取って 1.5 秒待機
    ...
```

ただ、上記 gist の例の様な確実で細やかな対応を行いたい場合、`ws_connect` メソッドが `Awaitable[aiohttp:ClientWebSocketResponse]` を返却する様にするか、何らかの方法でコネクションを指定して（`ws_connect` メソッドに `name: str` 引数を追加してコネクションごとに名前を付ける？）任意のタイミングで `send_str`, `send_json` できる様な双方向通信のためのインターフェイスを露出してあげる必要があるかと思います。

**Comment by MtkN1** [comment]
そうですね。`onopen`で制御可能にするのでいいかなというのはあるのですが、やはりユーザーが皆そうしなくてはいけないのは面倒だと思うのでpybotters側で自動制御したいなというのもあります。

ws_connectは切断された場合でも再接続を行って途中でコネクションが変わったりするので `Awaitable[aiohttp:ClientWebSocketResponse]` を外だししてもメインルーチン内で制御するというのは中々難しいかもしれません。

pybotters側で自動制御する場合は、継承した`pybotters.ws.ClientWebSocketResponse(aiohttp.ClientWebSocketResponse)`クラスのsend_jsonをオーバーライドしてGMOだけなんとかできないかなっていうのを検討中です。。

**Comment by MtkN1** [comment]
上記案pybotters側で自動制御対応してみました 7a5dc79d61b87640d703f9e8fae4aefcb116254d

サーバータイムなら1秒判定確実かなと思ってそれで判定してみましたw
幸いGMO Public APIは特にレート制限はなさそうだったので

**Comment by supermomonga** [comment]
お、なるほど。良いと思います！
