### ISSUE TITLE
Linter, Formatter を導入したい

### ISSUE THREAD

**Issue by supermomonga** [MtkN1/pybotters#59]
プロジェクトで利用する Linter や Formatter を決定して、統一されたルールでコードをコミットしたい

## 背景

現状、手元では [Pyright](https://github.com/microsoft/pyright)（VSCode [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) 拡張経由）での静的型チェックが通り、 [black](https://github.com/psf/black) でコードフォーマットが行われた状態で Pull request を出しています。ただ、この辺りのツールは人によって好みが違うため、プロジェクトで採用ツールが定められていればそれに従ってコードを提出できるため嬉しいです。

また、ツールが定められていれば、GitHub Actions でのチェックや [git pre-commit hook](https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA-Git-%E3%83%95%E3%83%83%E3%82%AF) を用いたコミット前のチェック自動化などが検討できるかと思います。

**Comment by MtkN1** [comment]
提案ありがとうございます！
blackとflake8を導入しましょう。

**Comment by supermomonga** [comment]
ありがとうございます！

**Comment by MtkN1** [comment]
TODO:
- [ ] コードにflake8適用
- [ ] 自動化の設定
