### ISSUE TITLE
GMO コインの DataStore を実装する

### ISSUE THREAD

**Issue by supermomonga** [MtkN1/pybotters#60]
related: #20

----

既に手元で実装したものがあるのですが、自作 bot 用に一部分のデータしか管理していないため、網羅したのち Pull Request します。

**Comment by MtkN1** [comment]
助かります！是非よろしくお願いします🙇‍♂️

**Comment by MtkN1** [comment]
マージ後 `trades` と `ticker` も追加したので本Issueはクローズします。

**Comment by supermomonga** [comment]
ありがとうございます！
