### ISSUE TITLE
FTXDataStore の orders チャネルにおける close されたオーダーの取り扱いについて

### ISSUE THREAD

**Issue by kaznak** [MtkN1/pybotters#75]
FTXDataStore  を使用して WebSocket API を利用した BOT を作成しています。
そのなかで IOC オーダーを post した後、その執行状況(どの程度fillされたかなど)を確認してから次のループを実行したいと思っています。

このとき store.orders を利用して執行状況を確認できればよいのですが、[現状の実装では close されたオーダーは store.orders から削除される実装になっています](https://github.com/MtkN1/pybotters/blob/2f8504fa798ebddacda9ae13edafa56816bffeea/pybotters/models/ftx.py#L166
)。
一方で IOC オーダーは直ちに close されるため、 store.orders からは取得できず、やむなく都度 REST API を発行して対応しています。

一応実装はできているのですがレートリミットもこわいので、 store.orders から close されたオーダーも取得できるようにはならないでしょうか。よろしくお願いします。

**Comment by MtkN1** [comment]
## アイディア

- ① onmessage時削除されないようにする
  - ユーザーが手動でclose済みオーダーを削除するメソッドが必要
- ② onmessageはそのままでストアにデータキューみたいなものを持たせる
  - アクティブオーダーのみ管理できるメリットはそのままに執行状況などより高度な実装が可能になるかもしれない

**Comment by kaznak** [comment]
的はずれな issue ではなくて良かったです。

①はシンプルですね。僕自身はとりあえずこれが挙動を理解しやすくてよい気がしています。

削除のメソッドの実装としては、 store.get/store.find の亜種として、マッチしたレコードを返し、ストアからはレコードを削除するようなメソッドを用意するのが良いように思います。今の _delete の実装も get とほとんど同じなので、 find でも作れそうですし、他のチャネルのデータにも使えそうです。

②はどのようなものですか？ストアに新たにキューを追加して、 closed なオーダーがそちらに移される実装でしょうか。
orderbook の sorted メソッドの挙動が何となく似ていそうですね。

**Comment by MtkN1** [comment]
プルリクありがとうございます！ 確認しますので少々お待ちください。

②のアイディアは、もう少し考えた結果 `store.order.wait` メソッドを拡張する案です。
現状waitメソッドは次のメッセージがあるまで待機するメソッドですが戻り値はありません。
この戻り値として次に受信するメッセージが取得(キューイング)できれば、オーダーストアでは残らないデータを取得できるので即時キャンセルされたのか約定されたのか執行状況を確認することが可能かと思います。

**Comment by kaznak** [comment]
> ②のアイディアは、もう少し考えた結果 store.order.wait メソッドを拡張する案です。
それは良いアイディアですね。実際のところ約定状況はほとんどの場合で一度だけしか必要でないので、僕のユースケースではそれで十分です。また、他のケースでも一度だけしかデータが必要ないケースは、まあまある印象があります。
あとは find などと同じようにクエリが使用できて、かつ他のデータでも wait で新着のデータが取れれば、互換性を保ったままコードの結構な部分ががシンプルになりそうです。

僕の実装は _delete と find の拡張で、①のケースの削除の実装です。よろしくお願いします。

**Comment by kaznak** [comment]
自分の理解している範囲で簡単に実装してみました。いかがでしょうか。

**Comment by MtkN1** [comment]
コントリビュートありがとうございました！
マージしましたので本Issueはクローズします。
